name: Descargar y subir EPG

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # Ejecuta todos los días a las 6:00 UTC

jobs:
  sync-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar tu repositorio
        uses: actions/checkout@v3

      - name: Descargar archivo EPG
        run: |
          curl -L -o mm.color.xml.gz https://github.com/davidmuma/EPG_dobleM/raw/refs/heads/master/guiatv_color.xml.gz

      - name: Confirmar cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add mm.color.xml.gz
          git commit -m "Actualización automática de mm.color.xml.gz" || echo "Sin cambios que confirmar"

      - name: Subir a tu repositorio
        run: git push
